module.exports = {
    plugins: ['stylelint-order'],
    rules: {
        // Turn on order plugin
        'order/order': [
            'dollar-variables',
            'custom-properties',
            'declarations',
            { 'type': 'at-rule' },
            'rules',
            { 'type': 'at-rule', 'hasBlock': true }
        ],

        'order/properties-order': [
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'position',
                    'z-index',
                    'top',
                    'right',
                    'bottom',
                    'left'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'display',
                    'box-orient',
                    'line-clamp',
                    'visibility',
                    'float',
                    'clear',
                    'overflow',
                    'overflow-x',
                    'overflow-y',
                    'overflow-scrolling',
                    'clip',
                    'zoom',
                    'flex',
                    'flex-grow',
                    'flex-direction',
                    'flex-order',
                    'flex-pack',
                    'flex-align',
                    'flex-flow',
                    'flex-basis',
                    'flex-shrink',
                    'flex-wrap',
                    'justify-content',
                    'align-content',
                    'align-items',
                    'align-self',
                    'order',
                    'grid',
                    'grid-area',
                    'grid-template',
                    'grid-template-areas',
                    'grid-template-columns',
                    'grid-template-rows',
                    'grid-auto-columns',
                    'grid-auto-flow',
                    'grid-auto-rows',
                    'grid-column',
                    'grid-column-end',
                    'grid-column-start',
                    'grid-row',
                    'grid-row-end',
                    'grid-row-start'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'box-sizing',
                    'width',
                    'min-width',
                    'max-width',
                    'height',
                    'min-height',
                    'max-height',
                    'margin',
                    'margin-top',
                    'margin-right',
                    'margin-bottom',
                    'margin-left',
                    'padding',
                    'padding-top',
                    'padding-right',
                    'padding-bottom',
                    'padding-left'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'table-layout',
                    'empty-cells',
                    'caption-side',
                    'border-spacing',
                    'border-collapse',
                    'list-style',
                    'list-style-position',
                    'list-style-type',
                    'list-style-image'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'font',
                    'font-family',
                    'src',
                    'font-size',
                    'font-weight',
                    'font-style',
                    'font-variant',
                    'font-size-adjust',
                    'font-stretch',
                    'font-effect',
                    'font-emphasize',
                    'font-emphasize-position',
                    'font-emphasize-style',
                    'font-smooth',
                    'line-height',
                    'content',
                    'quotes',
                    'counter-reset',
                    'counter-increment',
                    'resize',
                    'cursor',
                    'user-select',
                    'nav-index',
                    'nav-up',
                    'nav-right',
                    'nav-down',
                    'nav-left',
                    'text-align',
                    'text-align-last',
                    'vertical-align',
                    'white-space',
                    'text-decoration',
                    'text-emphasis',
                    'text-emphasis-color',
                    'text-emphasis-style',
                    'text-emphasis-position',
                    'text-indent',
                    'text-justify',
                    'letter-spacing',
                    'word-spacing',
                    'text-outline',
                    'text-transform',
                    'text-wrap',
                    'text-orientation',
                    'text-overflow',
                    'text-overflow-ellipsis',
                    'text-overflow-mode',
                    'word-wrap',
                    'word-break',
                    'tab-size',
                    'hyphens',
                    'pointer-events',
                    'caret-color',
                    'direction'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'opacity',
                    'color',
                    'border',
                    'border-width',
                    'border-style',
                    'border-color',
                    'border-top',
                    'border-top-width',
                    'border-top-style',
                    'border-top-color',
                    'border-right',
                    'border-right-width',
                    'border-right-style',
                    'border-right-color',
                    'border-bottom',
                    'border-bottom-width',
                    'border-bottom-style',
                    'border-bottom-color',
                    'border-left',
                    'border-left-width',
                    'border-left-style',
                    'border-left-color',
                    'border-radius',
                    'border-top-left-radius',
                    'border-top-right-radius',
                    'border-bottom-right-radius',
                    'border-bottom-left-radius',
                    'border-image',
                    'border-image-source',
                    'border-image-slice',
                    'border-image-width',
                    'border-image-outset',
                    'border-image-repeat',
                    'outline',
                    'outline-width',
                    'outline-style',
                    'outline-color',
                    'outline-offset',
                    'background',
                    'background-color',
                    'background-image',
                    'background-repeat',
                    'background-attachment',
                    'background-position',
                    'background-position-x',
                    'background-position-y',
                    'background-clip',
                    'background-origin',
                    'background-size',
                    'object-fit',
                    'object-position',
                    'box-decoration-break',
                    'box-shadow',
                    'text-shadow',
                    'mask',
                    'filter',
                    'highlight-color',
                    'fill'
                ]
            },
            {
                'emptyLineBefore': 'always',
                'noEmptyLineBetween': true,
                'properties': [
                    'transition',
                    'transition-delay',
                    'transition-timing-function',
                    'transition-duration',
                    'transition-property',
                    'transform',
                    'transform-origin',
                    'animation',
                    'animation-name',
                    'animation-duration',
                    'animation-play-state',
                    'animation-timing-function',
                    'animation-delay',
                    'animation-iteration-count',
                    'animation-direction'
                ]
            }
        ]
    },
};
